# Generated by Django 5.1 on 2024-08-20 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Malzeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=200, verbose_name='Наименование')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Примичение')),
                ('miktar', models.FloatField(verbose_name='Количество')),
            ],
            options={
                'verbose_name_plural': 'Материал',
            },
        ),
        migrations.CreateModel(
            name='Malzeme_birim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
            ],
            options={
                'verbose_name_plural': 'Измерение единиц',
            },
        ),
        migrations.CreateModel(
            name='Malzeme_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
            ],
            options={
                'verbose_name_plural': 'Категория материала',
            },
        ),
        migrations.CreateModel(
            name='GirisHareketi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miktar', models.FloatField(verbose_name='Количество')),
                ('tedarikci', models.CharField(max_length=200, verbose_name='Поставщик')),
                ('giris_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Дата поступления')),
                ('malzeme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.malzeme', verbose_name='Материал')),
            ],
        ),
        migrations.CreateModel(
            name='CikisHareketi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miktar', models.FloatField(verbose_name='Штук')),
                ('uretim_siparisi', models.CharField(max_length=200, verbose_name='Производсвенный заказ')),
                ('cikis_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Дата выпуска')),
                ('malzeme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.malzeme', verbose_name='Материал')),
            ],
        ),
        migrations.AddField(
            model_name='malzeme',
            name='malzeme_birim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.malzeme_birim', verbose_name='Едиица измерение'),
        ),
        migrations.AddField(
            model_name='malzeme',
            name='malzeme_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.malzeme_category', verbose_name='Category'),
        ),
        migrations.CreateModel(
            name='TransferHareketi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miktar', models.FloatField(verbose_name='Штук')),
                ('transfer_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Дата передачи')),
                ('hedef_ambar', models.CharField(max_length=200, verbose_name='Целевой склад')),
                ('malzeme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.malzeme', verbose_name='Материал')),
            ],
        ),
    ]
