# Generated by Django 5.1 on 2024-08-20 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Город')),
            ],
            options={
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Цвет')),
            ],
            options={
                'verbose_name_plural': 'Цвет кроя',
            },
        ),
        migrations.CreateModel(
            name='Kroy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('kroy_no', models.CharField(max_length=20, verbose_name='Крой номер')),
                ('ras_tkani', models.FloatField(verbose_name='Расход ткани')),
                ('ras_dublerin', models.FloatField(verbose_name='Расход дублерин')),
                ('edinitsa', models.IntegerField(blank=True, null=True, verbose_name='Единица')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Примечение')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name_plural': 'Крой',
            },
        ),
        migrations.CreateModel(
            name='Operation_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Примечение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name_plural': 'Код оперции',
            },
        ),
        migrations.CreateModel(
            name='Product_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип одежды',
                'verbose_name_plural': 'Тип одежды',
            },
        ),
        migrations.CreateModel(
            name='Kroy_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pachka', models.CharField(max_length=200, verbose_name='Пачка')),
                ('razmer', models.CharField(max_length=200, verbose_name='Размер')),
                ('rost', models.CharField(max_length=200, verbose_name='Рост')),
                ('stuk', models.IntegerField(verbose_name='Штук')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Примечение')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.city', verbose_name='Город')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.colors', verbose_name='Цвет')),
                ('kroy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kroy', verbose_name='Крой')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Крой детально',
            },
        ),
        migrations.CreateModel(
            name='Masterdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('в процессе', 'в процессе'), ('завершень', 'завершень')], default='в процессе', max_length=50)),
                ('kroy_no', models.CharField(max_length=50, verbose_name='Крой номер')),
                ('edinitsa', models.IntegerField(verbose_name='Единица')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Примечение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('confirmation', models.BooleanField(default=False, verbose_name='Подтверждение')),
                ('operations', models.CharField(max_length=150, verbose_name='Операция')),
                ('type_product', models.CharField(max_length=150, verbose_name='Тип одежды')),
                ('price', models.IntegerField(verbose_name='Единица')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('operation_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.operation_code', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Общая таблица',
            },
        ),
        migrations.CreateModel(
            name='Kroy_operation_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('kroy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kroy', verbose_name='Крой')),
                ('operation_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.operation_code', verbose_name='Код оперции')),
            ],
            options={
                'verbose_name_plural': 'Применить операцию на крой',
            },
        ),
        migrations.CreateModel(
            name='Operation_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('operation_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.operation_code', verbose_name='Код оперции')),
            ],
            options={
                'verbose_name_plural': 'Список оперции',
            },
        ),
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('kroy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kroy', verbose_name='Крой')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product_type', verbose_name='Тип одежды')),
            ],
            options={
                'verbose_name_plural': 'Операции',
            },
        ),
        migrations.AddField(
            model_name='operation_code',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product_type', verbose_name='Тип одежды'),
        ),
    ]
