# Generated by Django 5.1 on 2024-08-23 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('main', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kroy',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='client.client', verbose_name='Клиент'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kroy',
            name='order',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Клиент'),
            preserve_default=False,
        ),
    ]
