# Generated by Django 5.0.1 on 2024-02-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kroy',
            name='kroy_no',
            field=models.CharField(max_length=20, verbose_name='Крой номер'),
        ),
    ]
