# Generated by Django 5.0.1 on 2024-02-13 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdata',
            name='confirmation',
            field=models.BooleanField(default=False, verbose_name='Подтверждение'),
        ),
    ]
