# Generated by Django 5.0.1 on 2024-02-12 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_kroy_kroy_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Город')),
            ],
            options={
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Свет')),
            ],
            options={
                'verbose_name_plural': 'Свет кроя',
            },
        ),
        migrations.AddField(
            model_name='kroy_detail',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.city', verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kroy_detail',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.colors', verbose_name='Пользователь'),
            preserve_default=False,
        ),
    ]
