# Generated by Django 5.0.1 on 2024-02-12 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_city_colors_kroy_detail_city_kroy_detail_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colors',
            options={'verbose_name_plural': 'Цвет кроя'},
        ),
        migrations.AddField(
            model_name='masterdata',
            name='confirmation',
            field=models.BooleanField(default=True, verbose_name='Подтверждение'),
        ),
        migrations.AlterField(
            model_name='colors',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='kroy_detail',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='kroy_detail',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.colors', verbose_name='Цвет'),
        ),
    ]
