# Generated by Django 5.1 on 2024-08-26 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_status_alter_masterdata_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Статус'},
        ),
        migrations.AlterField(
            model_name='masterdata',
            name='kroy_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kroy', verbose_name='Крой номер'),
        ),
        migrations.AlterField(
            model_name='masterdata',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.status', verbose_name='Статус'),
        ),
    ]
