# Generated by Django 5.1 on 2024-08-28 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0005_alter_status_options_alter_masterdata_kroy_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterdata',
            name='user_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Группа пользователя'),
            preserve_default=False,
        ),
    ]
