# Generated by Django 5.1 on 2024-08-28 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_masterdata_user_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdata',
            name='operation_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.operation_code', verbose_name='Код операции'),
        ),
        migrations.AlterField(
            model_name='masterdata',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
    ]
