# Generated by Django 4.2.13 on 2024-08-28 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_masterdata_operation_code_and_more"),
    ]

    operations = []
