# Generated by Django 4.2.13 on 2024-08-28 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = []
